version: '3'
services:
  golf-api:
    build:
      context: .
      dockerfile: GolfApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: YourPassword123!
      ACCEPT_EULA: Y

  golf-client:
    build:
      context: .
      dockerfile: GolfClient/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - golf-api
